spring:
  redis:
    host: localhost
    port: 6379
    password: mhc123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  datasource:
    url:
    username: root
    password: 188158

my: